[package]
name = "cpumon"
version = "0.1.0"
edition = "2024"
description = "A lightweight, real-time per-core CPU usage monitor"
license = "AGPL-3.0-or-later"
repository = "https://github.com/arghyadipchak/cpumon"
keywords = ["cpu", "monitor", "system", "cli", "performance"]
categories = ["command-line-utilities", "hardware-support"]

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "4.6.6", features = ["derive", "color"] }
core_affinity = "0.8.3"
ctrlc = "3.5.2"
duration-string = "0.5.3"
sysinfo = "0.39.6"
thiserror = "2.0.20"

[build-dependencies]
clap = { version = "4.6.6", features = ["derive"] }
clap_complete = "4.6"
duration-string = "0.5.3"
sysinfo = "0.39.6"
thiserror = "2.0.20"

[profile.release]
panic = "abort"
strip = true
lto = true
codegen-units = 1
